# Blog posts
from datetime import datetime

post_data = [{
    "theme": 1,
    "title": "Phang Nga Bay: a day in paradise",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-01 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-01 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_01.jpg",
    "picture_v_source": "https://pixabay.com/photos/phang-nga-bay-phuket-province-2076833/",
    "picture_s": "Picture_s_01.jpg",
    "picture_s_source": "https://pixabay.com/photos/mountains-tropical-thailand-2129544/",
    "picture_h": "Picture_h_01.jpg",
    "picture_h_source": "https://pixabay.com/photos/thailand-phang-nga-bay-beach-sea-180828/",
    "picture_alt": "Phang Nga Bay",
    },
    {
    "theme": 1,
    "title": "A waterfall trail in the Californian Coast is what you need right now",
    "author_id": 6,
    "date_submitted": datetime.strptime("2023-01-11 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-11 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_02.jpg",
    "picture_v_source": "https://pixabay.com/photos/beach-waterfall-coastal-california-1630472/",
    "picture_s": "Picture_s_02.jpg",
    "picture_s_source": "https://pixabay.com/photos/beach-waterfall-sea-nature-1630475/",
    "picture_h": "Picture_h_02.jpg",
    "picture_h_source": "https://pixabay.com/photos/san-francisco-california-beach-4271367/",
    "picture_alt": "Californian Coast",
    },
    {
    "theme": 1,
    "title": "What brought me to Cape Town's Boulder Beach in 2022",
    "author_id": 7,
    "date_submitted": datetime.strptime("2023-01-16 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-17 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_03.jpg",
    "picture_v_source": "https://pixabay.com/photos/cape-town-boulder-beach-penguin-5741110/",
    "picture_s": "Picture_s_03.jpg",
    "picture_s_source": "https://pixabay.com/photos/penguins-birds-animals-3994532/",
    "picture_h": "Picture_h_03.jpg",
    "picture_h_source": "https://pixabay.com/photos/cape-town-boulder-beach-penguin-5741110/",
    "picture_alt": "Boulder Beach",
    },
    {
    "theme": 2,
    "title": "The ancient city of Dubrovnik is a stunner",
    "author_id": 7,
    "date_submitted": datetime.strptime("2023-01-17 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-17 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_04.jpg",
    "picture_v_source": "https://pixabay.com/photos/buildings-street-dubrovnik-croatia-4352262/",
    "picture_s": "Picture_s_04.jpg",
    "picture_s_source": "https://pixabay.com/photos/dubrovnik-croatia-adriatic-red-5100607/",
    "picture_h": "Picture_h_04.jpg",
    "picture_h_source": "https://pixabay.com/photos/dubrovnik-croatia-kings-landing-512798/",
    "picture_alt": "Dubrovnik",
    },
    {
    "theme": 4,
    "title": "Petra is the way Jordan reminds the world of the roots of civilization",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-18 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-18 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_05.jpg",
    "picture_v_source": "https://pixabay.com/photos/canyon-landmark-petra-jordan-4358577/",
    "picture_s": "Picture_s_05.jpg",
    "picture_s_source": "https://pixabay.com/photos/jordan-petra-holiday-middle-east-181912/",
    "picture_h": "Picture_h_05.jpg",
    "picture_h_source": "https://pixabay.com/photos/petra-jordan-travel-world-heritage-3839666/",
    "picture_alt": "Petra",
    },
    {
    "theme": 2,
    "title": "And I quote 'half of my heart is in Havana, ooh na-na",
    "author_id": 7,
    "date_submitted": datetime.strptime("2023-01-19 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-19 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_06.jpg",
    "picture_v_source": "https://pixabay.com/photos/cyprus-limassol-old-town-old-house-2638534/",
    "picture_s": "Picture_s_06.jpg",
    "picture_s_source": "https://pixabay.com/photos/cars-old-car-vehicle-cuba-oltimer-1638594/",
    "picture_h": "Picture_h_06.jpg",
    "picture_h_source": "https://pixabay.com/photos/havana-cuba-city-urban-sea-wharf-4027210/",
    "picture_alt": "Havana",
    },
    {
    "theme": 4,
    "title": "The Cambodian trip to renew your energies and clean your soul",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-20 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-21 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_07.jpg",
    "picture_v_source": "https://pixabay.com/photos/angkor-thom-angkor-wat-cambodia-1349581/",
    "picture_s": "Picture_s_07.jpg",
    "picture_s_source": "https://pixabay.com/photos/angkor-wat-temple-amazing-934094/",
    "picture_h": "Picture_h_07.jpg",
    "picture_h_source": "https://pixabay.com/photos/buddhism-asia-boys-cambodia-1822518/",
    "picture_alt": "Cambodja",
    },
    {
    "theme": 3,
    "title": "Kenya is perfect for that Safari you had in mind",
    "author_id": 6,
    "date_submitted": datetime.strptime("2023-01-20 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-21 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_08.jpg",
    "picture_v_source": "https://pixabay.com/photos/cheetahs-animals-safari-5689873/",
    "picture_s": "Picture_s_08.jpg",
    "picture_s_source": "https://pixabay.com/photos/safari-africa-tree-piste-kenya-1029078/",
    "picture_h": "Picture_h_08.jpg",
    "picture_h_source": "https://pixabay.com/photos/africa-kenya-safari-wildlife-4058720/",
    "picture_alt": "Kenya safari",
    },
    {
    "theme": 3,
    "title": "The Andes like you've never seen before: a spetacular setting",
    "author_id": 6,
    "picture_v": "Picture_v_09.jpg",
    "date_submitted": datetime.strptime("2023-01-20 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-21 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v_source": "https://pixabay.com/photos/patagonia-argentina-landscape-5173688/",
    "picture_s": "Picture_s_09.jpg",
    "picture_s_source": "https://pixabay.com/photos/pink-flamingos-birds-lake-nature-6558751/",
    "picture_h": "Picture_h_09.jpg",
    "picture_h_source": "https://pixabay.com/photos/lama-ecuador-cotopaxi-91978/",
    "picture_alt": "Andes in Ecuador",
    },
    {
    "theme": 3,
    "title": "Touring the Rio Negro is not for the faint of heart",
    "author_id": 6,
    "date_submitted": datetime.strptime("2023-01-22 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-22 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_10.jpg",
    "picture_v_source": "https://pixabay.com/photos/jaguar-panther-zoo-safari-nature-7393553/",
    "picture_s": "Picture_s_10.jpg",
    "picture_s_source": "https://pixabay.com/photos/amazon-forest-nature-trees-outdoor-4769367/",
    "picture_h": "Picture_h_10.jpg",
    "picture_h_source": "https://pixabay.com/photos/brazil-rainforest-amazon-rio-negro-69588/",
    "picture_alt": "Amazon forest",
    },
    {
    "theme": 2,
    "title": "Tokio is where the ultramodern and the traditional mix under the opulent Mount Fuji",
    "author_id": 7,
    "date_submitted": datetime.strptime("2023-01-24 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-25 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_11.jpg",
    "picture_v_source": "https://pixabay.com/photos/boat-cherry-blossom-park-river-1835081/",
    "picture_s": "Picture_s_11.jpg",
    "picture_s_source": "https://pixabay.com/photos/tokyo-japan-shibuya-night-4807294/",
    "picture_h": "Picture_h_11.jpg",
    "picture_h_source": "https://pixabay.com/photos/tokyo-japan-city-asia-fuji-urban-4358758/",
    "picture_alt": "Tokio",
    },
    {
    "theme": 4,
    "title": "I've been to the 'Land of Kings' and this is what I learned - a girl in Rajasthan",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-24 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-25 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_12.jpg",
    "picture_v_source": "https://pixabay.com/photos/architecture-chomu-palace-rajasthan-639103/",
    "picture_s": "Picture_s_12.jpg",
    "picture_s_source": "https://pixabay.com/photos/india-rajastan-strong-amber-1457098/",
    "picture_h": "Picture_h_12.jpg",
    "picture_h_source": "https://pixabay.com/photos/india-rajastan-jaisalmer-palace-919195/",
    "picture_alt": "Rajasthan",
    },
    {
    "theme": 4,
    "title": "Egypt: travelling in time",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-27 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-27 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_13.jpg",
    "picture_v_source": "https://pixabay.com/photos/temple-architecture-buildings-4687909/",
    "picture_s": "Picture_s_13.jpg",
    "picture_s_source": "https://pixabay.com/photos/hieroglyphs-pharaohs-egypt-luxor-429863/",
    "picture_h": "Picture_h_13.jpg",
    "picture_h_source": "https://pixabay.com/photos/egypt-desert-egyptian-temple-giza-1179193/",
    "picture_alt": "Egypt",
    },
    {
    "theme": 2,
    "title": "Digital nomads should check out these Budapest coffee shops",
    "author_id": 5,
    "date_submitted": datetime.strptime("2023-01-30 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "date_to_post": datetime.strptime("2023-01-30 00:10:00", '%Y-%m-%d %H:%M:%S'),
    "picture_v": "Picture_v_14.jpg",
    "picture_v_source": "https://pixabay.com/photos/scape-budapest-parliament-92603/",
    "picture_s": "Picture_s_14.jpg",
    "picture_s_source": "https://pixabay.com/photos/budapest-hungary-632851/",
    "picture_h": "Picture_b_14.jpg",
    "picture_h_source": "https://pixabay.com/photos/matthias-church-church-night-lights-4516471/",
    "picture_alt": "Budapest",
    }
]

post_intro = "Drawn by the Stones: A Journey to Boulder Beach"
post_body = """<h2>Drawn by the Stones: A Journey to Boulder Beach</h2>
<p>In 2022, something unspoken pulled me south — to Cape Town, to the rugged hush of Boulder Beach.</p>

    <p>The sky hung low, the sea whispered against black sands, and giant stones stood like ancient guardians watching over the shore.<br>
    In their shadows, I felt small, yet strangely whole — as if the vastness of it all was not to shrink me, but to set me free.</p>

    <p>I didn't come for the perfect skies or golden sands.<br>
    I came for this: the wildness, the weight of time, the sound of the earth breathing.</p>

    <p>At Boulder Beach, every step is a poem, every wave a memory.<br>
    I came seeking silence.<br>
    I found a voice.</p>
"""
